[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --filter=web... --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter=@taskflow/types build || true",
  "pnpm --filter=@taskflow/validators build || true",
  "pnpm --filter=web build"
]

[start]
cmd = "npx serve dist -l $PORT --single"
